[2024-10-03T07:48:53.903+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-03T07:48:53.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v3.print_version scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T07:48:53.983+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v3.print_version scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T07:48:53.986+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-10-03T07:48:54.021+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): print_version> on 2024-10-02 00:00:00+00:00
[2024-10-03T07:48:54.063+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T07:48:54.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v3', 'print_version', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_py_dependencies.py', '--cfg-path', '/tmp/tmpprvkufql']
[2024-10-03T07:48:54.067+0000] {standard_task_runner.py:63} INFO - Started process 224 to run task
[2024-10-03T07:48:54.068+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask print_version
[2024-10-03T07:48:54.194+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v3.print_version scheduled__2024-10-02T00:00:00+00:00 [running]> on host fb5d174c2391
[2024-10-03T07:48:54.399+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v3' AIRFLOW_CTX_TASK_ID='print_version' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2024-10-03T07:48:54.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-03T07:48:54.427+0000] {logging_mixin.py:188} INFO - Python version: 3.12.3 (main, Apr 24 2024, 11:28:46) [GCC 12.2.0]
[2024-10-03T07:48:54.428+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-03T07:48:54.432+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-03T07:48:54.452+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v3, task_id=print_version, run_id=scheduled__2024-10-02T00:00:00+00:00, execution_date=20241002T000000, start_date=20241003T074853, end_date=20241003T074854
[2024-10-03T07:48:54.494+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-03T07:48:54.531+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T07:48:54.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
