[2024-10-03T08:02:39.679+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-03T08:02:39.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL_JsonData.unzip scheduled__2024-10-01T08:01:00+00:00 [queued]>
[2024-10-03T08:02:39.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL_JsonData.unzip scheduled__2024-10-01T08:01:00+00:00 [queued]>
[2024-10-03T08:02:39.734+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-10-03T08:02:39.753+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): unzip> on 2024-10-01 08:01:00+00:00
[2024-10-03T08:02:39.764+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=838) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T08:02:39.764+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL_JsonData', 'unzip', 'scheduled__2024-10-01T08:01:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/ETLProject/main.py', '--cfg-path', '/tmp/tmpm6207fd4']
[2024-10-03T08:02:39.766+0000] {standard_task_runner.py:63} INFO - Started process 847 to run task
[2024-10-03T08:02:39.766+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask unzip
[2024-10-03T08:02:39.827+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL_JsonData.unzip scheduled__2024-10-01T08:01:00+00:00 [running]> on host fb5d174c2391
[2024-10-03T08:02:39.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_ETL_JsonData' AIRFLOW_CTX_TASK_ID='unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T08:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T08:01:00+00:00'
[2024-10-03T08:02:39.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-03T08:02:39.980+0000] {logging_mixin.py:188} INFO - Lỗi khi giải nén file:[Errno 2] No such file or directory: 'C:/Users/adunh/Downloads/og_item_impression.20240830_/og_item_impression.20240830_1100_1.json.gz'
[2024-10-03T08:02:39.980+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-03T08:02:39.982+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-03T08:02:39.996+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_ETL_JsonData, task_id=unzip, run_id=scheduled__2024-10-01T08:01:00+00:00, execution_date=20241001T080100, start_date=20241003T080239, end_date=20241003T080239
[2024-10-03T08:02:40.062+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-03T08:02:40.077+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
